travis:
  secure:
    BINSTAR_TOKEN: DFNachM7mYiJIdxcTeEgaIZBWnrTS0uQsvUJnWr3+FCHrDcFT9vU5A6bN2GS+x4UpQufm2XNYk7HgM2GfI3Wx5Q5OTox0JF5Mj9yNlEboko8GvI4+3iHEb4e43dwAT56BwWAPtMK/9KZYUdgwBhjgKq3ley8RHhvqM4HpUnyKYDCb8hiLwXpUMTMCmjqkRJjiPVGxEzj6c6lAOaSrvL2/QPp+k9kMvgJM9TmO8sjlGHEuZ5GSn+25QGzDiIsE9YJQIq0LMny6AepfwJ8bQbz/7IvRFSiZfx9ByIXPXVTWYPunXP/dG+T13j5wXpiqwykBT/iIkMKSvnULfxcKWF8GLrE+cEgAWHo+2vbNU5kbPxdsuNQOfg0WLaTtjA4/8DssOX5GqHwOsKRjat0+ClOUQJe6o3aAWm+MEL9dNbuK+iRUyhbYm6r+zDqNkTtn4M0sMVt9OYm0WNG/r9Ide7JI/iKMrfoHRPDT0SbDKEVlTSsWTURl2Q8pgkw3ZR9AjAlbxvjcODlA0Ad1gxrYRpgnsn3z7rI39MCgrMT5N2A7cn5DVLeCwmDkC+EwmbQf10CqwBSJLCzKSDFmkGa5SNDyYSlQkaBvkiw3zA5pwz48AGezg/Wt9Efaz10y+/SkeRDPuM3zY9ypLS+bNoR5AA90OOQKdUNPV2fLvZTyMrbT/E=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
