travis:
  secure:
    BINSTAR_TOKEN: gPqy/qYxsPl1SWyyQQbTvyMdqy32IO/+13B4vahcTmfOMVSEQyfZK5t7Yf2RV9VqIrOHdoonOJ+fnyMNFGpFHeIaAdZSjYdGqRwMQWvARtVdUKkjr2qhyAzdB9elIw5JPJ20GvDByQymPlGbzs72ZzB51PwwAZaBi6U7yBzoN/+0jDkgHvxeu35rjTSRKIDHucwSOLAJHsZ70k+80V5a8d/nWuS4+r4zQMX/PGN2rvzTcsDFgaIzHxxitOcYO79Jo4ZGULCvUro7mVJtWvUtWr27OQtBdr4xoEif8xs36xBy51FjudWfu8vZ5ZN8aY6BrtSKD2gx82PimpfpHNTEoFx3LU0tQXuiJWn6r6Mr5VYCPs4c0h9/V2I6r2fx9Undmuqm1jYHfPg2146ik8cIZcIFzXv3WP9ESiCApxazqlkkqH086oNq9fjthEWIrcEAjwviDQtDiD/n0E2Kw6B30a5aeIbCnLTXV8CcYebjG4hygni9XeybohCAbG6VWBJAgoQWae+IY8cLdInZqQ2ixWcLTjsfBlQk6Nq2xpc1IoyHV9NVlYDTlI0W8iGJgVdT4tvRV3orFxz2FKtKuALaCHv64+5WuVJ5pn0LK72Mjm0JSv1icPy75Mxg7V2AuSpzL2ytd3USfoDu4Dk1IlhHFZOxU6vIGXN44r7ci3M5jAg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
